version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container-name: uitime_backend
    restart: unless-stopped
    ports:
      - "5068:8080"
    env_file:
      - ./backend/.env
    enviroment:
      - ASPNETCORE_ENVIRONMENT=Production

  bot:
    build:
      context: ./bot
    container_name: uitime_bot
    restart: unless-stopped
    depends_on: 
      - backend
    env_file: 
      - ./bot/.env